services:
  db:
    build: .
    container_name: pg_s2
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sandbox
    volumes:
      - pgdata:/var/lib/postgresql/data
  dev:
    build:
      context: .
      target: builder
    working_dir: /workspace
    volumes:
      - .:/workspace

volumes:
  pgdata:
